### ISSUE TITLE
Eclipse launch configuration argument variables not expanded?

### ISSUE THREAD

**Issue by ksamborn** [eclipse/buildship#546] opened 2017-08-09 22:18 UTC
I think that with Buildship 2.1.2, variables in the "Arguments" tab in a Gradle Eclipse Launch Configuration are no longer expanded.

For example, if I use ${string_prompt}, the variable is never expanded, and Gradle tries to execute a task with the name ${string_prompt}.

Below is the console output using buildship itself as my project and running the "help" task.

Am I missing something?

If this is an issue, I'm not 100% sure, but I think this was introduced when the method getConfigurationAttributes().toFixedRequestAttributes() was no longer called in BaseLaunchReqestJob (in PR #459) 

I'm not sure if this affects other variables in the Launch Configuration, like in the environment or other tabs.

Thanks,
Kevin

--

Working Directory: C:\Users\k\Documents\buildship
Gradle User Home: C:\Users\k\.gradle
Gradle Distribution: Gradle wrapper from target build
Gradle Version: 2.14.1
Java Home: C:\Program Files\Java\jdk1.8.0_101
JVM Arguments: None
Program Arguments: ${string_prompt}
Build Scans Enabled: false
Offline Mode Enabled: false
Gradle Tasks: help

:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE

FAILURE: Build failed with an exception.

* What went wrong:
Task '${string_prompt}' not found in root project 'buildship'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.535 secs

**Comment by donat** [comment] 2017-10-13 10:39
@ksamborn  Sorry for the late reply, but we already fixed this issue. You can go ahead and try the latest Buildship snapshot.

**Comment by donat** [comment] 2017-10-13 10:39
Duplicate of #572.

**Closed by donat** 2017-10-13 10:39 UTC
Labels: a:bug

**Comment by ksamborn** [comment] 2017-10-13 11:41
Thanks, Donat
