### ISSUE TITLE
Support debug Gradle test

### ISSUE THREAD

**Issue by Camork** [eclipse/buildship#752] opened 2018-08-28 07:21 UTC
We can only lanuch a gradle tester in 'run' mode now, is there any plan to support debug it? Also there should be able to set the run configuration to customize the jvm args.

**Comment by donat** [comment] 2018-08-28 08:15
Yes, we have the intention to support Gradle invocations in debug mode. To give you a short overview, the plan is to first finish 3.0 with the new stable APIs, then implement task execution upon synchronization, and then comes the debug support. Prioritization might change over time, but the main indicator we use what should come next is the number of 👍 on the issues.

FYI, you can already set arguments and JVM arguments in the run configurations dialog.

**Comment by donat** [comment] 2018-08-28 08:15
Duplicate of https://github.com/eclipse/buildship/issues/249.

**Closed by donat** 2018-08-28 08:15 UTC
