### ISSUE TITLE
Test dependencies on testFixtures are not working in gradle 6.7

### ISSUE THREAD

**Issue by JWood48** [eclipse/buildship#1037] opened 2020-11-16 10:36 UTC
After upgrading from gradle 6.6.1 to 6.7

testImplementation testFixture(project(":core"))

is not working anymore.

The testFixture dependency is not available on the test build path of the project referencing it in eclipse!

### Expected Behavior
the test fixture dependency should be available on the build path where required

### Current Behavior
testFixture classes are not available on projects requesting the testFixture

### Steps to Reproduce 
* Take example project from issue #991: [test-plan](https://github.com/eclipse/buildship/files/4569313/eclipse-gradle-bug.zip)
* upgrade gradle version to 6.6.1 (./gradlew wrapper --gradle-version 6.6.1)
* Import in eclipse -> the orginal error from #991 is still there, but the test source compiles since the reference to the testFixture works for test sources
* upgrade to gradle 6.7 (./gradlew wrapper --gradle-version 6.7)
* Run gradle refresh from eclipse
* Now the test sources from the test project show an error due to missing testFixture dependency

### Your Environment
Gradle 6.7
Buildship:  3.1.4.v20200326-1743
Eclipse: 2020-09 (eclipse.buildId=4.17.0.I20200902-1800)

**Comment by karstenrenhak** [comment] 2020-11-17 09:51
https://github.com/gradle/gradle/issues/14932

**Comment by donat** [comment] 2021-02-03 13:47
Duplicate of https://github.com/eclipse/buildship/issues/1009

It still works again with Gradle 6.8.

**Closed by donat** 2021-02-03 13:47 UTC
Labels: a:bug :beetle:
