### ISSUE TITLE
APT not takein into account while importing project

### ISSUE THREAD

**Issue by eximius313** [eclipse/buildship#486] opened 2017-06-05 10:55 UTC
I have Gradle project that uses ```apt``` plugin (```apply plugin: 'net.ltgt.apt'```)

When I use ```./gradlew eclipse``` task, it recognizes and creates APT bindings:
```
:eclipseClasspath
:eclipseJdt
:eclipseProject
:eclipse
:backend:eclipseClasspath
:backend:eclipseFactorypath
:backend:eclipseJdt
:backend:eclipseJdtApt
:backend:eclipseProject
:backend:eclipse
```
creates ```.factorypath``` file:
```
<factorypath>
  <factorypathentry kind='EXTJAR' id='C:\Users\U\.gradle\caches\modules-2\files-2.1\org.projectlombok\lombok\1.16.16\245b50f714bf89ed7659266ace12f9e509d13551\lombok-1.16.16.jar' enabled='true' runInBatchMode='false' />
  <factorypathentry kind='EXTJAR' id='C:\Users\U\.gradle\caches\modules-2\files-2.1\org.mapstruct\mapstruct-processor\1.2.0.Beta2\5eb4495e9e78d7eef8c5a5a90813ee2edfed1fdc\mapstruct-processor-1.2.0.Beta2.jar' enabled='true' runInBatchMode='false' />
</factorypath>
```
and ```.settings/org.eclipse.jdt.apt.core.prefs```
```
eclipse.preferences.version=1
org.eclipse.jdt.apt.aptEnabled=true
org.eclipse.jdt.apt.genSrcDir=.apt_generated
org.eclipse.jdt.apt.reconcileEnabled=true
```

but when I import the project using Buildship - APT is just ignored

**Comment by oehme** [comment] 2017-06-06 13:33
This is a combination of #267 and #265. If these two were implemented, then the APT plugin could tell Gradle that it needs some additional preferences and that it also needs to generate some additional file. Right now this information is opaque to Buildship. We can't just run the `eclipse` task, because that would break some of Buildship's features like a portable classpath container.

I'm closing this as a duplicate of #267 and #265. Please add your vote to these two.

**Closed by oehme** 2017-06-06 13:33 UTC
