### ISSUE TITLE
Gradle multi-project project containing project with multiple source sets uses incorrect classpath at launch time

### ISSUE THREAD

**Issue by onmishkin** [eclipse/buildship#1034] opened 2020-10-16 22:07 UTC
### Expected Behavior
Suppose project A depends on project B and project B has multiple source sets. Then if I launch a class in project A the launched JVM's classpath should include class folders associated with all of project B's source sets.

### Current Behavior
All of project B's classes are _not_ included in the classpath and a ClassNotFoundException results.

### Context
This behavior start with Buildship 2.2.2. When installing all versions of Eclipse starting with 2018-12 we've had to uninstall the version of Buildship that comes with Eclipse and then install Buildship 2.2.1. However, Buildship 2.2.1 doesn't work with Eclipse 2020-09. (Eclipse 2020-09 requires Java 11 and Buildship 2.2.1 seems to not be able to handle the version string that Java 11 reports.)

### Steps to Reproduce 
Import the attached Gradle project into Eclipse and then launch the _subproj1_ class.
[mmp-test.tar.gz](https://github.com/eclipse/buildship/files/5394507/mmp-test.tar.gz)

**Comment by sanderkerel** [comment] 2020-11-12 12:25
I am not sure, but this sounds similar to the problem described in this pullrequest: https://github.com/gradle/gradle/pull/14534

But there the fix is not in buildship but in the eclipse plugin, which is part of gradle. The problem is that it generates only correct classpath references for the test and main sourcesets.

The fix is in this merge commit: https://github.com/gradle/gradle/commit/606d75b3c0e683a61cf15f751bcbd1d71851d532

If you want to try it out yourself you can try upgrading to gradle 6.8, which is only available in the nightlies at this moment  https://gradle.org/nightly/

I tested it by simply printing the classpath variable in a main method: `System.out.println(System.getProperty("java.class.path").replace(';', '\n'));`

**Comment by onmishkin** [comment] 2020-11-30 14:26
> I am not sure, but this sounds similar to the problem described in this pullrequest: [gradle/gradle#14534](https://github.com/gradle/gradle/pull/14534)

This seems to be the case because I just tried things out with Gradle 6.8 Milestone 3 and the problem is gone. Thanks for the tip @sanderkerel!

**Closed** 2021-02-03 15:34 UTC
Labels: a:bug :beetle:
