### ISSUE TITLE
Presence of JDK9 causes Eclipse Oxygen 4.7.1a and STS 3.9.0 to fail with Buildship 2.1.2.v20170807

### ISSUE THREAD

**Issue by corporate-gadfly** [eclipse/buildship#610] opened 2017-11-06 01:49 UTC
Filing this from my mobile device, so no screenshots or project details, but thought it was worth filing.

Essentially, I can't create a new "Gradle Project". Neither can I import an "Existing Gradle Project. I get the same screenshot as in this [post](http://dev.eclipse.org/mhonarc/lists/buildship-dev/msg00021.html).
![screenshot](http://dev.eclipse.org/mhonarc/lists/buildship-dev/pngvA3Kcf6wRt.png)

**Comment by donat** [comment] 2017-11-06 13:24
All model queries are logged to the `[Gradle Model Retrievals]` console. If you open the Console view it should be already on the list of open consoles and you should see some sort of exception related to the wizard.

**Comment by corporate-gadfly** [comment] 2017-11-06 14:28
Unfortunately the console is not there _(hopefully I'm looking in the correct place)_
This is what I see in the Console View:
![Console View](https://user-images.githubusercontent.com/1200537/32445608-4893ad8c-c2d4-11e7-8e8a-e32948444d86.png)
I do have JDK 9 installed but it is *not* the default JDK.
![Installed JREs](https://user-images.githubusercontent.com/1200537/32445706-9e26683e-c2d4-11e7-9066-47d008c18ca3.png)
Any other ideas? Are you able to reproduce on your side?

**Comment by donat** [comment] 2017-11-06 14:54
The console selector is this one:
<img width="584" alt="screen shot 2017-11-06 at 22 51 16" src="https://user-images.githubusercontent.com/419883/32446897-5fe6cd9a-c345-11e7-8c66-04b944afc996.png">

**Comment by corporate-gadfly** [comment] 2017-11-07 01:18
So, I uninstalled JDK9 and the problem went away. I'm able to create a new Gradle project as well import Existing Gradle project.

Feel free to close this issue _(in favour of another issue)_, if you feel like it.

**Comment by donat** [comment] 2017-11-07 01:30
Oh, I forgot about that the latest Buildship release is incompatible with Java 9. Sorry about that. 
We fixed this problem in the latest milestone, you can give it a go if you want. I'm closing this issue as duplicate of #601

**Closed by donat** 2017-11-07 01:30 UTC
