### ISSUE TITLE
All test-task will be executed on Gradle Test

### ISSUE THREAD

**Issue by jmattheis** [eclipse/buildship#489] opened 2017-06-07 14:00 UTC
Gradle Version: 3.5
Eclipse Version: 4.6.3 (Neon.3)
Buildship Version: 2.0.2.v20170420-0909

Currently the `Run as -> Gradle Test` executes the test on all modules and on all available test-tasks.
In our project there are various integration test-tasks therefore it is not wanted that they all will be executed (as well if the test is skipped, the server will still be started). 

It should be possible to configure which test-task should be executed.

Related: #409

**Comment by oehme** [comment] 2017-06-07 14:06
Closing as duplicate of #409. Please add your vote there 👍

**Closed by oehme** 2017-06-07 14:06 UTC

**Comment by jmattheis** [comment] 2017-06-07 16:10
Its not exactly a duplicate as this is primarily about what `test`-task should be executed and other issue is about on what project the tests should be executed.

**Comment by oehme** [comment] 2017-06-07 16:36
That's essentially the same thing, everything is about task selection in the end.
