### ISSUE TITLE
Welcome page hard to read

### ISSUE THREAD

**Issue by PyvesB** [eclipse/buildship#928] opened 2019-10-07 10:19 UTC
Hello there!

On my macOS, the welcome page is very hard to read using the default light theme:
![Screenshot 2019-10-07 at 09 26 35](https://user-images.githubusercontent.com/10694593/66303930-08dee380-e8f4-11e9-8577-a553af7d2bc2.png)

Is anyone else facing the same issue?

Thanks!

Pyves

**Comment by donat** [comment] 2019-10-07 16:20
Fixed in https://github.com/eclipse/buildship/commit/234c03cd4651f02ff537e2a54fa732b162fc4ff9

**Comment by PyvesB** [comment] 2019-10-07 16:30
Thanks for the quick fix! 🎉

**Comment by donat** [comment] 2019-10-08 09:12
No problem. I wanted to ask you to test the latest snapshot, but unfortunately, the eclipse.org infrastructure team changed some permissions which broke our promotion builds. I'll post an update here when the issue is resolved.

**Comment by donat** [comment] 2019-10-09 14:16
@PyvesB the [latest snapshot](https://github.com/eclipse/buildship/blob/master/docs/user/Installation.md) contains the fix. Could you please install it verify that it fixes this problem?

**Closed** 2019-10-09 14:38 UTC
Labels: a:bug :beetle:
