### ISSUE TITLE
BuildShip doesn't support Hibernate Metamodel Generator 

### ISSUE THREAD

**Issue by eximius313** [eclipse/buildship#594] opened 2017-10-13 18:41 UTC
I had a fresh installation of Gradle and Eclipse and I checked out existing project that uses Hibernate Metamodel Generator.
Buildship checked out the project, downloaded jars, but I still had compilation errors related to missing Metamodel generated classed.
When I run: ```./gradlew eclipse``` it downloaded additional jars, so clearly they were not there:
```
$ ./gradlew eclipse
:backend:eclipseClasspath
:backend:eclipseFactorypath
Download https://repo1.maven.org/maven2/org/hibernate/hibernate-jpamodelgen/5.2.10.Final/hibernate-jpamodelgen-5.2.10.Final.pom
Download https://repo1.maven.org/maven2/org/hibernate/hibernate-jpamodelgen/5.2.10.Final/hibernate-jpamodelgen-5.2.10.Final.jar
:backend:eclipseJdt
:backend:eclipseJdtApt
:backend:eclipseProject
:backend:eclipse
```
After that project compiled successfuly

**Comment by donat** [comment] 2017-10-14 01:12
Hi! 
Buildship doesn't provide explicit support for Hibernate, so if there are extra classes added to the classpath then Eclipse might not see it. It can be fixed with a bit of customization of the classpath generation (examples [here](https://discuss.gradle.org/t/buildship-1-0-18-is-now-available/19012)). 
If you attach a sample project exhibiting the problem then I can have a closer look.

**Comment by eximius313** [comment] 2017-10-14 11:35
but ```eclipse``` task handled it without any problems, so something in Buildship is missing
The project is huge, but I'll try to provide sample in the nearest future

**Comment by oehme** [comment] 2017-10-16 06:14
This is because Buildship has no support for the `factoryPath` (a.k.a. annotation processor configuration) at the moment.

**Comment by eximius313** [comment] 2017-11-13 20:35
Is this related to https://github.com/eclipse/buildship/issues/267 ?

**Comment by oehme** [comment] 2017-11-14 16:14
Only if the factory path is a preference file. If it is a different file format (like .classpath), then it would be a separate issue.

**Comment by tbroyer** [comment] 2017-11-30 11:11
`.factoryPath` is **not** a preference file; it's XML, similar to `.classpath`. However, enabling annotation processing and configuring the (single!) output directory (and processor options, and whether processors are only called for batch compilation, or "in the editor") is done in a preference file: `.settings/org.eclipse.jdt.apt.core.prefs`.

Fwiw, my [`net.ltgt.apt`](https://github.com/tbroyer/gradle-apt-plugin`) plugin generates a `.factoryPath` and `.settings/org.eclipse.jdt.apt.core.prefs`; but it's far from ideal and I'd much rather see this built into Gradle/Buildship (if I could retire the plugin, that'd be ideal; `options.annotationProcessorPath` in Gradle 3.4 and `options.annotationProcessorGeneratedSourcesDirectory` in 4.3 are on the right track! and IDE support is basically all that's missing)
Fwiw, this is already tracked at #329 :tada:

**Comment by oehme** [comment] 2017-12-01 11:14
Thanks for the info @tbroyer! I agree that we should push support in Gradle further and also expose the info to Eclipse. We just need to move one step up from the `JavaCompile` task to modeling this on the `SourceSet` level. Then we can expose it through the eclipse model and let Buildship configure jdt.apt.

Closing as a duplicate of #329

**Closed by oehme** 2017-12-01 11:14 UTC

**Comment by tbroyer** [comment] 2017-12-01 12:34
I had proposed this some time ago as a design doc in the gradle/gradle repo; my idea being that `net.ltgt.apt` could be used as a testbed and "incubator", and things would eventually move to Gradle proper. See https://github.com/tbroyer/gradle-apt-plugin/blob/master/README.md#configuration (with the now-broken link to the design doc)
What's the new process for those kinds of proposals?

Also, what about processor arguments? (`-Akey=value` compiler args) It would probably be a good thing to configure them automatically in IDEs, but I'm not sure `SourceSet` would be the correct place to put them… (that said, I'm in the "delegate build/run actions to Gradle" camp, so configuring paths –like what's already possible in 4.3– is enough in this case)

**Comment by oehme** [comment] 2017-12-01 14:39
The problem with the factory path is just that the compile task doesn't expose the data in a way that we can use for the IDE (a `Configuration`), but instead as a simple `FileCollection`. That's why I want have a dedicated `Configuration` for it. But for things like processor args looking at the compile task would probably be fine.

**Comment by tbroyer** [comment] 2017-12-01 16:05
OK, so if you want to start implementing something in Buildship, you could do that already when the `net.ltgt.apt` plugin is applied (good luck reconciliating `sourceSets.main.aptConfigurationName` and `sourceSets.test.aptConfigurationName` though :wink:).

So, what's the process to propose such new features to be added to Gradle proper? (issue? forum? design doc?)

**Comment by oehme** [comment] 2017-12-01 16:21
A Github issue would be the way to go.

**Comment by tbroyer** [comment] 2017-12-08 17:28
This is already covered by https://github.com/gradle/gradle/issues/2300 right? Or should I file another issue for just the `annotationProcessorConfigurationName` part of it?

**Comment by oehme** [comment] 2017-12-08 17:36
You're right, that covers it all. t would be great if you could add things we should consider to that issue. I.e. what common usability issues are users facing today?

**Comment by ChristianCiach** [comment] 2018-05-16 16:17
Why is this issue closed? Even when gradle itself eventually exposes the configured annotation processors (I think it already does by now?), eclipse/buildship still has to create the eclipse configuration from it. So gradle/gradle#2300 will not automatically fix this issue for Buildship users.

**Comment by ChristianCiach** [comment] 2018-05-16 16:19
Right now, my build.grade file contains these dependencies:

```
    annotationProcessor group: 'com.google.auto.value', name: 'auto-value', version: '1.5.3'
    annotationProcessor group: 'com.ryanharter.auto.value', name: 'auto-value-gson', version: '0.7.0'
    annotationProcessor group: 'org.hibernate', name: 'hibernate-jpamodelgen', version: '5.2.12'

```

So these are explicitly configured in Gradle. Can't Buildship pick these up?

**Comment by fhackenberger** [comment] 2025-01-09 15:53
For a workaround in 2025: you can use a plug-in: https://stackoverflow.com/a/79343214/289064
