### ISSUE TITLE
Option for automatically refreshing project dependencies when build.gradle changes

### ISSUE THREAD

**Issue by wodencafe** [eclipse/buildship#581] opened 2017-09-24 14:40 UTC
Hi guys,

this feature request is for automatically refreshing the Eclipse Project's Dependencies when the dependencies change in the build.gradle file for a particular project, similar to a feature that Spring Tool Suite has:

![enable-auto-refresh](https://user-images.githubusercontent.com/9727493/30783658-5a44ecc4-a10c-11e7-97d9-702f05b16394.png)

Is this something that could be added to Buildship, to not have to manually refresh the project when the build.gradle dependencies change?

**Comment by donat** [comment] 2017-09-27 11:40
I like the idea. If anybody else needs this, please 👍 this issue, or better yet, submit a PR to the project.

**Comment by oehme** [comment] 2017-09-28 09:54
Duplicate of #335

**Closed by oehme** 2017-09-28 09:54 UTC
Labels: an:enhancement, help-wanted
