### ISSUE TITLE
Passing multiple arguments to gradlew in Run Configuration of STS4

### ISSUE THREAD

**Issue by hanct** [eclipse/buildship#880] opened 2019-05-03 18:04 UTC
Spring Tool Suite: v4.2.1 
Gradle: v5.3.1

I post in this forum cos BuildShip (Eclipse Grade Tooling) is  part of Spring Tool Suite. And my belong issue might be related to the BuildShip plugin.

Hi all,

I try passing multiple arguments to the gradle task (called bootRun) into my spring boot application via the STS Run configuration dialog box. 
![RunConfigurationSTS4](https://user-images.githubusercontent.com/4410920/57114115-4c985480-6d7a-11e9-8441-49e8a43ac476.png)

But an error was thrown as shown below
![RunConfigurationSTS4-result](https://user-images.githubusercontent.com/4410920/57114163-88cbb500-6d7a-11e9-8602-d6622e806b3b.png)

But yet, when i run on the same project using commandline (instead of STS4), it is successful
![gradlew-result](https://user-images.githubusercontent.com/4410920/57114227-d2b49b00-6d7a-11e9-8da9-1686b1aacbf6.png)

Is this a bug in the Buildship? Or is my configuration wrong? Even if i pass the entire string **--args="--data.server=remoteHost:999 --spring.main.banner-mode=off"** into the Program or JVM arguments of the Run Configuration dialog box, also no work.

**Comment by donat** [comment] 2019-05-28 11:46
The problem is that the `Tasks` text field splits the content on whitespaces. The fix should be similar to #624 .

**Comment by donat** [comment] 2019-05-31 07:12
The fix is merged and part of the latest snapshot. @hanct can you please give it a try?

**Closed by donat** 2019-05-31 07:12 UTC
Labels: a:bug :beetle:
