### ISSUE TITLE
Buildship fails to generate „project-preferences“ on Gradle project import — „Model not available for project.{$name}“

### ISSUE THREAD

**Issue by lingocoder** [eclipse/buildship#936] opened 2019-10-30 01:15 UTC
### Expected Behavior

Executing Eclipse's *`Run as — JUnit Test`* menu command for a Gradle *`init`*-generated JUnit test should successfully launch an Eclipse *`Run Configuration`*.

### Current Behavior

Executing Eclipse's *`Run as — JUnit Test`* menu command for a Gradle *`init`*-generated JUnit test fails with an internal Buildship error: „*`Model not available for com.company.mytest`*“.

### Context

Hi @donat. From the attached exception stack traces, I've established that the „*`Model not available for project.{$name}`*“ error message happens [*at this point in the code*](https://github.com/eclipse/buildship/blob/17909a1ddf5bc62f63d15f18d1bdf3de569d0665/org.eclipse.buildship.core/src/main/java/org/eclipse/buildship/core/internal/workspace/GradleClasspathContainerRuntimeClasspathEntryResolver.java#L77). 

My hypothesis is that the *`GradlePluginsRuntimeException`* is thrown because Buildship fails to generate the *`{$eclipse.workspace}/.metadata/.plugins/org.eclipse.buildship.core/project-preferences`* folder when the project is initially imported into Eclipse. That *best-guess* at the root cause, is based on my observation that restarting Eclipse causes the *`project-preferences`* folder and its project file to eventually be generated. 

After the folder and file are generated on a restart, running the test with *`Run as — JUnit Test`* successfully launches as expected. That can be observed in this screencast:

![mr jar buildship bug lab 0 b](https://user-images.githubusercontent.com/49788472/67833496-b51f7e80-fadc-11e9-9c4d-56f17759b4aa.gif)

### Steps to Reproduce<sup><sup>[*Download example project*](https://github.com/eclipse/buildship/files/3787223/buildship.bug.lab.0.a.zip)</sup></sup> 

1. Initialize a Gradle project from [*the online Gradle project initializer*](http://bit.ly/GradleInit)
    - Generate a: *Java Library*
    - with test framework: *JUnit 5*
    - with DSL: *Groovy*
    - with Gradle version: *5.6.2*
    - and archive format: *zip*
    - Project name: *com.company.mytest*
    - Package: *com.company.mytest*
    
2. Import the generated project into Eclipse
3. Open the „LibraryTest.java“ file in the editor
4. From Eclipse's „Run“ menu, select *`Run as — JUnit Test`*
5. Observe the following error:

```
'Launching LibraryTest' has encountered a problem.
An internal error occurred during: "Launching LibraryTest".
Model not available for com.company.mytest
```

6. Restart Eclipse with *File — Restart`*
7. Open the „LibraryTest.java“ file in the editor
8. From Eclipse's „Run“ menu, select *`Run as — JUnit Test`*
9. Observe the JUnit test runs as expected and succeeds

### Your Environment

```
Gradle Wrapper: version 5.6.2
Ecliipse: 2019-12 — eclipse.buildId=4.14.0.I20191009-1800
Buildship: 3.1.2.v20190903-1802
java.version=12
java.vendor=Oracle Corporation
OS: Windows amd64
```

**Comment by donat** [comment] 2019-10-30 09:34
I was able to reproduce the problem. Thanks @lingocoder for the elaborate steps, it was really helpful.

The root cause is that the root project has a custom name, which creates a wrong entry in the in-memory cached version of the preferences file loaded from `{$eclipse.workspace}/.metadata/.plugins/org.eclipse.buildship.core/project-preferences`. I'm going to provide a fix soon.

**Comment by lingocoder** [comment] 2019-10-30 10:47
Sincere thanks, @donat, for the speedy and attentive reply :+1:

>  „...*the root project has a custom name*...“

I'm confused by what you mean by: „*custom name*“, donat. Apologies.

Most of Gradle code in general — *and Buildship especially* — flies right over my head. But you've really *Whoosh*-ed me there :) 

I thought that all projects had a *custom name*. In that *custom*, in my mind, means a name explicitly chosen by the build author — versus a name auto-generated or in some other way *mandated* by the tool being used. Does it have a more specific meaning in the context of Buildship?

Are there any particular names — *or formats* —that are more likely to trigger the reported behavior?

**Comment by lingocoder** [comment] 2019-10-30 19:10
>> *...So I'm gonna install it in my current Eclipse using the `https://download.eclipse.org/buildship/updates/e413/snapshots/3.x` update site? Right?...*

I'm not having any luck with that update site donat...

![mr jar buildship bug lab 1 a](https://user-images.githubusercontent.com/49788472/67888121-78876d80-fb44-11e9-8623-bd05c87982d6.gif)

[*Here are the Eclipse logs from that session*](https://github.com/eclipse/buildship/files/3790625/buildship.debug.lab.1.a.error.logs.log).

I used the update site URL for the most recent version (*2019-09*) in your [*Update sites for Buildship 3.x*](https://github.com/eclipse/buildship/blob/master/docs/user/Installation.md#update-sites-for-buildship-3x) table. But, as noted in my ***Your Environment*** section above, I'm on *2019-12*.

Here's what I've tried so far:

* I tried editing the URL from *`e413`* to *`e414`*. But that failed with: „*`Could not find https://download.eclipse.org/buildship/updates/e414/snapshots/3.x`*“
* I tried *`File — Restart`* and also exiting out and relaunching. Neither with any luck.
* I thought I might have been locking the *`.plugins`* folder. So I closed anything that might have been holding that. No luck.
* I couldn't find snapshot versions of Buildship in *Eclipse Marketplace*. Nor could I uninstall the currently-installed version from there. I got the same error as above.

What else should I try? TIA.

**Comment by lingocoder** [comment] 2019-10-31 00:24
Hi donat,

I downloaded and installed 2019.09. Then I was successful at updating Buildship with your snapshot using the update site at: *`https://download.eclipse.org/buildship/updates/e413/snapshots/3.x`*

Sadly, importing [*that same project*](https://github.com/eclipse/buildship/files/3787223/buildship.bug.lab.0.a.zip) and trying to run its test, this time I get a *`Could not run test — No tests found with test runner 'JUnit5'`*...

![mr jar buildship bug lab 2 a](https://user-images.githubusercontent.com/49788472/67908319-09753d80-fb73-11e9-9ba9-59c943ed6dad.gif)

Let me know if you need more details?

**Comment by donat** [comment] 2019-10-31 08:32
I've seen the same thing, although I think it's a classpath-related issue and not a bug in Buildship. I'm closing this ticket now. Could you please post this problem to the Gradle forum, maybe somebody already has a working Eclipse project using Gradle, Junit5 and Java modules together.

**Closed by donat** 2019-10-31 08:32 UTC
Labels: a:bug :beetle:

**Comment by lingocoder** [comment] 2019-10-31 09:38
Cheers, donat

Will do.

Sincerest gratitude for you making that 2019.06 patch snapshot available. Is there, or will there be, a snapshot with the patch for 2019.12? If not, then what's the *rough* ETA for Milestone 3.1.3?

**Comment by donat** [comment] 2019-11-07 09:54
We'll do a release shortly after Gradle 6.0 comes out, which is already due in the next couple of days/weeks.
