### ISSUE TITLE
Buildship update sometimes fail with `No repository found containing ...` messages

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#415] opened 2017-03-08 09:09 UTC
[Original report](https://discuss.gradle.org/t/buildship-2-0-1-is-now-available/21810):

>When I try to upgrade from Buildship 1 to 2 it Eclipse 4.6, I get the errors below. So I uninstall Buildship 1 and remove its update site. Still I get the same errors trying to install Buildship 2. Then when Eclipse restarts, the Buildship 2 update URL has been replace with Buildship 1.
```
An error occurred while collecting items to be installed
session context was:(profile=_Users_thad_Applications_eclipse_java-neon_Eclipse.app_Contents_Eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,com.gradleware.tooling.client,0.18.0.v20170220163122
No repository found containing: osgi.bundle,com.gradleware.tooling.model,0.18.0.v20170220163122
No repository found containing: osgi.bundle,com.gradleware.tooling.utils,0.18.0.v20170220163122
No repository found containing: osgi.bundle,org.eclipse.buildship.branding,2.0.1.v20170302-1039
No repository found containing: osgi.bundle,org.eclipse.buildship.core,2.0.1.v20170302-1039
No repository found containing: org.eclipse.update.feature,org.eclipse.buildship,2.0.1.v20170302-1039
No repository found containing: osgi.bundle,org.eclipse.buildship.stsmigration,2.0.1.v20170302-1039
No repository found containing: osgi.bundle,org.eclipse.buildship.ui,2.0.1.v20170302-1039
No repository found containing: osgi.bundle,org.gradle.toolingapi,3.4.0.v20170220163122
```

**Comment by RobMaskell** [comment] 2017-05-08 08:28
Just received the same error trying to upgrade from buildship 1 to buildship 2

**Comment by oehme** [comment] 2017-07-31 12:24
Duplicate of #488

**Closed by oehme** 2017-07-31 12:24 UTC
Labels: a:bug
