### ISSUE TITLE
Tooltip shows wrong warning

### ISSUE THREAD

**Issue by UdoW** [eclipse/buildship#1190] opened 2022-07-22 10:50 UTC
Adding a different Gradle user home in the global preferences shows a wrong warning and tooltip.

### Expected Behavior

No warning is shown if the given path is existent.

### Current Behavior

A warning is shown like if I would have filled in something in the field "Java home".

See screen shot.
![wrong_tooltip](https://user-images.githubusercontent.com/12225215/180424224-241ec39d-7edc-4a1c-bf6d-6841ce7c1ebb.PNG)

### Steps to Reproduce 

Fill in an existent path into the field "Gradle user home".

### Your Environment

Eclipse 2022-06
Buildship 3.1.6

**Comment by TheKodeToad** [comment] 2022-09-15 08:45
This looks to be intentional to me.
The warning says that the settings will be non-portable. This is true. M:\gradle_user_home is unlikely to be present on other computers.

**Comment by cypher256** [comment] 2022-10-28 03:29
This is the same issue as #1171.

**Comment by donat** [comment] 2022-11-07 14:44
Closing as duplicate of https://github.com/eclipse/buildship/issues/1171.

**Closed** 2022-11-07 14:44 UTC
Labels: a:bug :beetle:
