### ISSUE TITLE
Gradle 3.4.1- Resolve dependencies .classpath, .runtimeclasspath

### ISSUE THREAD

**Issue by kbsasikarthik** [eclipse/buildship#826] opened 2018-12-12 19:50 UTC
Gradle won't resolve dependencies on .classpath and runtimeclasspath. It keeps on running forever. Only difference is I upgraded my OS to Windows 10. Tried re-installing STS and Gradle many times. My project requirement is to use Gradle 3.4.1 and STS 3.7.1

**Comment by kbsasikarthik** [comment] 2018-12-12 20:08
[STS_Problems.docx](https://github.com/eclipse/buildship/files/2673351/STS_Problems.docx)

**Comment by donat** [comment] 2018-12-17 14:47
I'm sorry but we cannot help without further details. If you have dependency resolution problems then chances are that the problem is not related to the IDE. If that's the case, please post your question at the Gradle forums. If the problem comes from the IDE attach a sample project or at least a stack trace here. 

I'm closing this issue to keep the project board clean.

**Closed by donat** 2018-12-17 14:47 UTC
