### ISSUE TITLE
STS "New Spring Starter Project" broken

### ISSUE THREAD

**Issue by edeandrea** [eclipse/buildship#525] opened 2017-07-14 12:53 UTC
This is in addition to #517, #518, & #519 

Starting with version 2.0.2 of the Buildship plugin the STS "New Spring Starter Project" functionality when choosing the Gradle (Buildship 2.x) type is broken. From what I've seen by people in my company there is a range of Eclipse & STS versions affected by Buildship >= 2.0.2. We have had to downgrade back to `2.0.1.v20170302-1039` in order to get things to work. Anything after `2.0.1.v20170302-1039` (snapshots/milestones) seems to break.

- Eclipse 4.6
- Eclipse 4.7
- STS 3.8.3
- STS 3.8.4
- STS 3.9.0

See the below screenshot for what the issue looks like.
![new spring starter project](https://user-images.githubusercontent.com/363447/28212840-635bae70-6871-11e7-8675-96a0c2653749.png)

**Comment by donat** [comment] 2017-07-18 14:11
Closing as duplicate of #524

**Closed by donat** 2017-07-18 14:11 UTC
Labels: a:bug

**Comment by edeandrea** [comment] 2017-07-18 17:03
I just verified that 2.1.2.v20170718-1426-s fixes this issue.

**Comment by donat** [comment] 2017-07-19 07:51
Thanks for checking @edeandrea!  FYI we tentatively scheduled the 2.0.2 release for July 24, 2017.
