### ISSUE TITLE
Multi-project EAR - "Cannot run tasks for included builds"

### ISSUE THREAD

**Issue by jsm174** [eclipse/buildship#393] opened 2017-02-21 17:41 UTC
I have a multi-project EAR with two skinny WARs and a utilities library. When I import the projects into Eclipse and "Add Gradle Nature" and then "Refresh Gradle Project", I do not see much in the console:

![screen shot 2017-02-21 at 12 34 34 pm](https://cloud.githubusercontent.com/assets/1197137/23176690/2e0eb2bc-f832-11e6-88dc-ac327b1d1d54.png)

I can not execute any tasks in the "Gradle Tasks" view. The options are all dimmed:

![screen shot 2017-02-21 at 12 23 18 pm](https://cloud.githubusercontent.com/assets/1197137/23176361/9d0604ce-f830-11e6-8b84-ab8ea4e72fae.png)

If I switch the configuration to two WARs and a utilities library (no EAR project), I can execute tasks without issues.

Is this the expected behavior?

Here is my EAR layout:

```
Root
   AdminWeb
   ServicesWeb
   Utilities
   EAR
```

Root/settings.gradle:

```
include 'Utilities'
include 'AdminWeb'
include 'ServicesWeb'
include 'EAR'

rootProject.name='Root'
```

Root/build.gradle:

```
apply plugin: 'eclipse'
apply plugin: 'eclipse-wtp'

subprojects {
   apply plugin: 'eclipse'
   apply plugin: 'eclipse-wtp'

   repositories {
      mavenCentral()
   }
}
```

Root/AdminWeb/build.gradle:

```
apply plugin: 'war'

dependencies {
   providedCompile project(':Utilities')
}
```

Root/ServicesWeb/build.gradle:

```
apply plugin: 'war'

dependencies {
   providedCompile project(':Utilities')
}
```

Root/Utilities/build.gradle:

```
apply plugin: 'java'

dependencies {
   compile ''
   .
   .
   . 
   compile fileTree(dir: 'libs', include: '*.jar')
}
```

Root/EAR/build.gradle:

```
apply plugin: 'ear'

dependencies {
   deploy project(path: ':AdminWeb', configuration: 'archives')
   deploy project(path: ':ServicesWeb', configuration: 'archives')
  
   earlib project(':Utilities')
}

```

**Comment by oehme** [comment] 2017-02-21 21:12
That's not expected, could you please push an example project to GitHub?

**Comment by jsm174** [comment] 2017-02-22 03:18
I pushed an example project at:

https://github.com/jsm174/buildship_ear_test

Steps to reproduce:

1. clone
2. gradle eclipse
3. import existing projects into workspace (search for nested projects checked)
4. add gradle nature
5. all tasks listed as "Cannot run tasks for included builds"

**Comment by oehme** [comment] 2017-02-22 07:15
@donat I think we should look at this before 2.0.1

**Comment by donat** [comment] 2017-02-22 08:35
Sure, I'll check it out soon.

**Comment by donat** [comment] 2017-02-22 11:16
I evaluated the example. Here's what I found:
- I could reproduce the problem when I followed your steps and added the Buildship nature to the `AdminWeb` project.
- When I repeated the steps and added the nature to the `Root` project, Buildship worked as expected.

In the code, the request attributes used for querying the Eclipse model contains a wrong project. We can fix by checking the root project in the returned model, adjusting the request attributes and do the second query if necessary. 

I have a prototype with the fix and I'll submit a PR soon.

**Comment by oehme** [comment] 2017-02-22 11:28
@donat If there is a workaround, let's not put this into 2.0.1

@jsm174 You always need to import/convert the root project, not some subproject. Also I noticed in your steps above that you first ran `gradle eclipse`. That's unnecessary. You can just use the "Import Gradle Project" wizard from Buildship to save several steps.

**Comment by jsm174** [comment] 2017-02-22 12:23
@oehme @donat Thank you very much for looking at this so quickly.

I was evaluating my repo strategy and was not sure if we would be committing our eclipse settings files. 

If we don't commit them, and use "Import Gradle Project", we must have the project cloned before using Eclipse. We usually just import "Projects from Git".

As for "Add Gradle Nature" to the Root project, I swear I tried that many times. But indeed that seems to work. I will go back to my real project and see if I can reproduce. 

FWIW, I do notice that immediately after "Add Gradle Nature" I still need to restart eclipse, as the Gradle Tasks view appears empty.

**Comment by oehme** [comment] 2017-02-22 13:00
You don't need to restart Eclipse, you could just click the refresh button on the tasks view.

@donat I guess the tasks view doesn't react properly to "Add Gradle Nature" yet? Might be worth a separate bug report.

**Comment by jsm174** [comment] 2017-02-22 13:11
@oehme Thanks. I found the refresh button and that does work!

**Comment by donat** [comment] 2017-02-22 13:39
@oehme I've created #395 for the tasks view sync problem.

**Comment by donat** [comment] 2017-02-22 13:41
Regarding the original problem, I think implementing #252 would resolve this issue too.

**Comment by oehme** [comment] 2017-02-22 13:42
I agree, let's close this as a duplicate of #252 and #395. Thank you for the report @jsm174! I hope the workaround is okay for you in the meantime.

**Closed by oehme** 2017-02-22 13:42 UTC
Labels: a:bug
