### ISSUE TITLE
An error occurred while update buildship by eclipse oxygen X64

### ISSUE THREAD

**Issue by cowcomic** [eclipse/buildship#555] opened 2017-08-25 08:43 UTC
eclipse remind me to update buildship
for version : 2.1.2.v20170807-1324
id : org.eclipse.buildship.feature.group

error occurred when i click finish
`
An error occurred while collecting items to be installed
session context was:(profile=D__Users_Administrator_eclipse_java-oxygen_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,com.gradleware.tooling.client,0.19.3.v20170801075239
No repository found containing: osgi.bundle,com.gradleware.tooling.model,0.19.3.v20170801075239
No repository found containing: osgi.bundle,com.gradleware.tooling.utils,0.19.3.v20170801075239
No repository found containing: osgi.bundle,org.eclipse.buildship.branding,2.1.2.v20170807-1324
No repository found containing: osgi.bundle,org.eclipse.buildship.core,2.1.2.v20170807-1324
No repository found containing: osgi.bundle,org.eclipse.buildship.stsmigration,2.1.2.v20170807-1324
No repository found containing: osgi.bundle,org.eclipse.buildship.ui,2.1.2.v20170807-1324
No repository found containing: osgi.bundle,org.gradle.toolingapi,3.5.0.v20170801075239
No repository found containing: org.eclipse.update.feature,org.eclipse.buildship,2.1.2.v20170807-1324
`

**Comment by regrog** [comment] 2017-08-28 12:08
check your repository : https://projects.eclipse.org/projects/tools.buildship/releases/2.1.2
Maybe your software site is incorrect.
I use this: http://download.eclipse.org/buildship/updates/e47/releases/2.x

**Comment by cowcomic** [comment] 2017-08-29 05:54
I use the same url : http://download.eclipse.org/buildship/updates/e47/releases/2.x
how to check my repository? I don`t understand the "repository" clearly, the maven repository?


btw my buildship version is 
"Buildship: Eclipse Plug-ins for Gradle	2.0.2.v20170420-0909	org.eclipse.buildship.feature.group	Eclipse Buildship"

eclipse remind me to update to version :
"Buildship: Eclipse Plug-ins for Gradle	2.1.2.v20170807-1324"

**Comment by cowcomic** [comment] 2017-08-29 06:07
another try, still error by update.
but install the new version done by "Install New Software", no error.

strange...

**Comment by donat** [comment] 2017-09-04 13:16
Duplicate of #488

**Closed by donat** 2017-09-04 13:16 UTC
