### ISSUE TITLE
Should use and support M2_REPO variable

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#361] opened 2017-02-08 16:52 UTC
Original post: https://bugs.eclipse.org/bugs/show_bug.cgi?id=507791

**Comment by digulla** [comment] 2017-03-20 16:43
Most likely a duplicate of bug #239.

**Comment by oehme** [comment] 2017-03-20 20:22
Buildship does not use variables, we already use a classpath container which encapsulates all dependencies.

**Closed by oehme** 2017-03-20 20:22 UTC
Labels: a:new-feature, source:bugzilla
