### ISSUE TITLE
Buildship classpath generation for Eclipse is broken

### ISSUE THREAD

**Issue by carlolf** [eclipse/buildship#509] opened 2017-07-04 13:34 UTC
Some weeks ago I noticed a compile error after refreshing the projects in Eclipse. On two of the subprojects, the Eclipse compiler complains on missing classes from Apache commons-lang3. This compile error is not present using Gradle on command line, and calling the Gradle compile dependency task at command line clearly shows the dependency:

`+--- org.apache.commons:commons-lang3:3.4`

So there must be some discrepancies between Gradle and Buildship regarding the classpath for the project.
Because the Eclipse container classpath is not editable, I have to add the Apache jar using "add external jar" (pointing to the Gradle cache).

**Comment by oehme** [comment] 2017-07-04 14:00
> So there must be some discrepancies between Gradle and Buildship regarding the classpath for the project.

Buildship uses what is configured in the `eclipse.classpath` model, which by default includes the main and test compile and runtime classpath. If your project needs any additional Configurations to compile in Eclipse you need to add them to `eclipse.classpath.plusConfigurations`.

Hope that helps, if not please provide a reproducible example project.

**Comment by carlolf** [comment] 2017-07-10 10:23
Hi Stefan,

> Buildship uses what is configured in the eclipse.classpath model, which by default includes the main and test compile and runtime classpath

If I run Buildship within Eclipse to clean and recreate Eclipse .classpath and .project files, then to my understanding, Buildship creates the Eclipse classpath dependencies from the Gradle build classpath. Therefore, when I call Gradle to show me dependencies from command line and it shows me that it knows the compile dependency which is missing in Eclipse, then I'm wondering what's wrong in this transformation. 
In my subproject, the commons-lang3 dependency is clearly a dependency from compile configurations.

That said, I suppose it would very difficult to give a reproducible example project. I think the problem only shows up in some constellations, which I cannot reproduce by a simple example.

**Comment by oehme** [comment] 2017-07-10 13:28
> In my subproject, the commons-lang3 dependency is clearly a dependency from compile configurations.

If it is in `compile`, it will be in Buildship unless you overwrote the default `eclipse.classpath` configuration in your build. I'm afraid I can't help without an example project.

**Comment by donat** [comment] 2017-08-15 09:07
Due to inactivity, I'm closing this project. Feel free to reopen it if there's an update.

**Closed by donat** 2017-08-15 09:07 UTC
