### ISSUE TITLE
Importing Projects Requires Immediate Clean

### ISSUE THREAD

**Issue by rwinch** [eclipse/buildship#375] opened 2017-02-13 15:34 UTC
When I import large projects into Eclipse with Buildship I often need to perform a clean build. For example, importing [Spring Session](https://github.com/spring-projects/spring-session) using Buildship results in errors like:

```
Description	Resource	Path	Location	Type
The project cannot be built until its prerequisite spring-session-data-redis is built. Cleaning and building all projects is recommended	spring-session-samples-boot-redis		Unknown	Java Problem
```

However, `spring-session-data-redis` will be built

**Comment by oehme** [comment] 2017-02-13 16:45
This is odd. Eclipse should normally rebuild projects as appropriate, as it notices changes to the classpath. Is this a new issue or has this been around for a while? Any cues as to why this happens might help.

**Comment by oehme** [comment] 2017-02-13 16:52
Moving to backlog as this might negatively affect many users with larger projects.

**Comment by rwinch** [comment] 2017-02-13 18:05
I'm not sure how long this has been happening. I can reproduce this consistently when importing Spring Session (I am pretty sure the problem occurs with spring-framework, spring-security, and spring-ldap too).

**Comment by oehme** [comment] 2017-02-13 18:09
Okay that's good to know. If it's consistent we can probably find the issue pretty quickly.

**Comment by donat** [comment] 2017-05-16 12:35
Hi @rwinch. I can't reproduce your problem. I tried importing the `Spring Session` project with the latest Buildship version and the projects were added and built correctly. I tried on Windows and on Mac, there was no difference. What Eclipse/Buildship/Gradle version did you use for the import?

**Comment by donat** [comment] 2017-11-16 01:12
I'm closing this ticket as inactive. Feel free to reopen it if you can reproduce the problem.

**Closed by donat** 2017-11-16 01:12 UTC
Labels: a:bug, waiting:contributor
