### ISSUE TITLE
Provide simple way to perform tasks on import

### ISSUE THREAD

**Issue by rwinch** [eclipse/buildship#374] opened 2017-02-13 15:27 UTC
It would be nice if there would be an easy way to perform some tasks on import. For example, the Spring Framework build depends on some generated classes. Importing with Buildship currently requires users to trigger the source generation manually rather than having the project import with a single command.

I expect that this integration would NOT require writing custom Eclipse plugin code. One idea is to automatically invoke some tasks before import, perform an import, then automatically invoke some tasks after import.

**NOTE** This is related to #326 but a reduced scope.

**Comment by oehme** [comment] 2017-02-13 16:48
This is a duplicate of #265. See that ticket for how we'd like to solve this, in case you or someone else is interested in contributing.

**Closed by oehme** 2017-02-13 16:48 UTC
