### ISSUE TITLE
Can I get all tasks for a gradle project?

### ISSUE THREAD

**Issue by simonjhy** [eclipse/buildship#830] opened 2018-12-18 06:38 UTC
I want to get all task applied in my gradle project include added by gradle and other gradle plugin added tasks?

**Comment by donat** [comment] 2018-12-18 08:36
Can you elaborate a bit on what are you trying to achieve?

**Comment by simonjhy** [comment] 2018-12-19 07:39
I created a new issue(#831 ) about this.

**Comment by donat** [comment] 2018-12-19 09:14
Duplicate of #831.

**Closed by donat** 2018-12-19 09:14 UTC
Labels: a:question
