### ISSUE TITLE
How to install Buildship and Xtext 2.14 in same Eclipse?

### ISSUE THREAD

**Issue by UdoW** [eclipse/buildship#734] opened 2018-08-20 14:19 UTC
I want to use Buildship (3.x SNAPSHOT) and Xtext 2.14 in same Eclipse (Photon).

Xtext depends on Guava 21. Buildship depends on Guava 15.

When building  a product with both features Guava 21 is selected, so Buildship's dependencies cannot be resolved.

How could I proceed?

**Comment by donat** [comment] 2018-08-21 08:34
Closing as duplicate of #285 .

**Closed by donat** 2018-08-21 08:34 UTC

**Comment by UdoW** [comment] 2018-08-21 09:54
There is a Buildship 3.x SNAPSHOT release already in your repository. I tried to intergrate that in my new release but couldn't because of old version of Guava.

When do you change the version of Guava in the SNAPSHOT release? Is there a change date defined already?

**Comment by donat** [comment] 2018-08-21 09:57
It's not precisely defined, but it's part of our next big sprint. If you install [ZenHub](https://github.com/eclipse/buildship#issue-tracking) into your browser you can check the [progress](https://github.com/eclipse/buildship/pulls#reports?report=burndown&milestoneId=2647009).

**Comment by UdoW** [comment] 2018-08-21 11:27
I figured out this new target for Eclipse 4.8:

    <location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
       <unit id="com.google.gson" version="2.7.0.v20170129-0911"/>
       <unit id="com.google.guava" version="21.0.0.v20170206-1425"/>
       <unit id="org.junit" version="4.12.0.v201504281640"/>
       <unit id="org.slf4j.api" version="1.7.10.v20170428-1633"/>
       <repository location="http://download.eclipse.org/tools/orbit/downloads/drops/R20180606145124/repository/"/>
    </location>

I cannot figure out how to successfully build and test everything on my Windows machine. The call "gradlew build" stopped with the error:

    > Task :installTargetPlatform FAILED". 
    [ant:taskdef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.

**Comment by donat** [comment] 2018-08-21 14:02
Interesting. I have a recollection of the same problem reported on windows, however, it never happens on our CI infrastructure. 

The problem occurs in the [build sources](https://github.com/eclipse/buildship/blob/master/buildSrc/src/main/groovy/eclipsebuild/mavenize/DeployMavenAntTaskExecutor.groovy#L32). The script tries to load an ant task from a dependency jar. I'd put a few `println` statements around there to see what's going on.

**Comment by UdoW** [comment] 2018-08-22 04:31
Why don't you use Tycho to build your Eclipse feature?
