### ISSUE TITLE
Issues creating new subproject 

### ISSUE THREAD

**Issue by gpaglia** [eclipse/buildship#471] opened 2017-05-15 14:14 UTC
Hello,

I am trying to create a new subproject in a multiproject setup, organized in a hierarchy:

master/
           |---subproject1/
           |---subproject2/
           |---....
           |---subprojectN/

Each subproject's root is directly within the master project's root folder. No further nesting.
I need to create a new subproject and I am using the 'Create new Gradle project' wizard,; I direct the wizard to create the new project within the root directory of the master project (a sibling of the other subprojects).
The new project gets created, with a skeleton build.gradle and a settings.gradle configuring the new subproject as a standalone project.
Then I delete the settings.gradle of the newly created project and I update the settings.gradle of the master project to 'include' the  new subproject.
After doing this, and re-syncing the whole multiproject, I end up with all gradle tasks locked (the icons are grey instead of green), the context menu on the tasks says that I cannot run tasks on includedBuilds.
The ".settings/org.eclipse.buildship.core.prefs" files of the master project and all of the subprojects except for the last one (in alphabetic order, let's say subprojectN) have the "connection.project.dir" property set to "../subprojectN".
The only way I found to fix this situation is to delete all projects from the Eclipse workspace (without on-disk deletion) and re-import in Eclipse the master project from file system, and do a 'gradle refresh'.

I noted that the same situation occurs if I import the master project and one or more of the subprojects into Eclipse.

One more piece of info: acting at gradlew level, everything seems normal, all tasks are listed and can be executed from the command line.

My environment is:
Windows 7 Professional
Eclipse Neon 3 on x-86
Gradle 3.5 (also 3.4.1 is the same)
Buildship v. 2.0.2v20170420-0909 (I had the same behaviour on 2.0.1)

Thanks a lot for any help,
GP.

**Comment by oehme** [comment] 2017-06-06 12:53
This is an unfortunate combination of two issues: 

- Instead of connecting to the root project, Buildship connected to the newly added subproject when you hit "Refresh". This is covered by #252 
- Our detection of composite builds is a bit fuzzy, leading to the misleading error message

The workaround until we fix these: Instead of hitting "Refresh" on the new subproject, hit "Refresh" on the existing root project instead.

**Comment by oehme** [comment] 2017-06-06 12:53
Closing as duplicate of #252

**Closed by oehme** 2017-06-06 12:53 UTC
