### ISSUE TITLE
Filtered project import

### ISSUE THREAD

**Issue by rotty3000** [eclipse/buildship#975] opened 2020-03-09 18:26 UTC
Ability to filter the set of projects imported to Eclipse.

### Expected Behavior
Only projects matching a predicate would be imported into Eclipse

### Context
I have a multi-project build laid out as a tree. Some of the sub-directories are only for aggregation directories and contain nothing but other sub-projects (i.e. no `build.gradle`). However buildShip imports these as empty projects. One of the annoying side effect is that, in Eclipse search, results will be returned from these projects.

It would be great if one could provide a closure that would allow projects to be filtered before being imported.

**Comment by donat** [comment] 2020-03-19 15:21
Duplicate of #247.

**Comment by donat** [comment] 2020-03-19 15:22
@rotty3000 please add a 👍 on #247 so that we could prioritize the work.

**Closed by donat** 2020-03-19 15:21 UTC
Labels: a:new-feature
