### ISSUE TITLE
Import dialog ends with exception: WTP currently does not support mixed deployment paths.

### ISSUE THREAD

**Issue by moley** [eclipse/buildship#697] opened 2018-05-02 06:14 UTC
Hi, 

I think I have found a buildship bug when importing a project, which applies ear plugin. 
I have stripped my usecase to a little demo project and uploaded it to https://github.com/moley/buildshipImportError. 

It contains two independent projects (mylib and myapp). 
mylib is a multi project and publishes different artifacts (beans which should contain things to be deployed, client and shared which contain things, which should be copied to lib dir of ear. the beans project has a dependency to shared. 
myapp contains the application itself containing only one subproject (myapp-ear)

This is - I guess - a valid approach. It is working with idea, but not with eclipse (neither oxygen nor latest photon). 

Steps to reproduce:
- call ./gradlew publishToMavenLocal in mylib
- call ./gradlew eclipse in myapp
- Import the myapp via File->Import->Existing Gradle Project (Next->Next->Finish, no further configurations)
- The error dialog comes the way

Would be nice if you can fix the bug and also provide a workaround in the meantime, because this blocks us from working with eclipse in this project.

Cheers
Markus

**Comment by moley** [comment] 2018-06-05 10:08
Hi, any news on this issue? Do you need additional things to reproduce/fix?

**Comment by lukeu** [comment] 2018-06-05 21:16
Can't say I have any experience with ear plugins (well, not since my days of playing in a band...) but I wonder if [this post](https://discuss.gradle.org/t/wtp-currently-does-not-support-mixed-deployment-paths/20404/24) might contain some info. E.g. this workaround stops the error dialog, if that's acceptable:

    eclipse.classpath.minusConfigurations << configurations.deploy

It also mentions the error dialog is intentional to highlight some Eclipse limitation (?) but is claimed to be non-fatal  non-blocking. (Not that I'd call having it pop up on every Gradle Refresh Project a workable solution.)

Finally just an observation that using `gradlew eclipse` and Importing Gradle Projects are usually mutually exclusive.
 * The former is a manual generation step and should be used with [Import > Existing (standard) Projects into workspace] - i.e. not making use of Buildship.
 * The latter uses Buildship to import, and does not require running `gradlew eclipse`. (Although I've found closing

**Comment by moley** [comment] 2018-06-06 09:59
I am musician too, but not using "in ear - plugins" yet. Only at work :-) 

Thank you for your workaround. This works partially for me. 

In some projects it's OK, but I have projects, where I have a dependency as both compile dependency and deploy dependency - and for this scenario I get compile errors in my project because this dependency is compeletly removed from buildpath in eclipse :-) 
As you have said this is an eclipse limitation can you estimate if this will be fixed in eclipse and if yes - when?

Perhaps this error can only be thrown if the wtp plugin is installed?

Cheers
Markus

**Comment by oehme** [comment] 2018-06-06 13:53
Yes, we should definitely only fail if WTP is installed.

The problem is that the WTP plugin does not allow you to make the deployment path of individual libraries inside a dependency container. It only lets you mark the whole container. So having both `deploy` and `earlib` with Buildship and WTP is not possible at the moment :(

**Comment by moley** [comment] 2018-06-07 06:55
Hi Stefan, 

Thanks for clearification - this helps me a lot. Do you know if WTP plugin has any plans to fix this limitation? By the way - Is using **deploy** and **earlib** at the same time such an abnormal use case? Or do I have to model my project in a different way? Do you know how others do this?

Kind regards
Markus

**Comment by oehme** [comment] 2018-06-07 07:18
The Maven team already tried to convince the WTP team, but that [discussion](https://bugs.eclipse.org/bugs/show_bug.cgi?id=128851) went nowhere. It seems the maintainer was not aware that you can have different deploy paths. He only added a "no deploy" option.

I think having both deploy and earlib is a perfectly normal use case, we're just limited by what WTP gives us. The only workaround I can think of would be splitting Buildship's classpath container into two when WTP is enabled, which would be pretty invasive and expensive on our side.

**Comment by moley** [comment] 2018-06-07 08:50
Ok, thank you for the info. So - I think our only hope is this discussion getting new drive again in the future and meanwhile I think we will recommend our developers to use no WTP plugin or to use IntelliJ instead (which is not my own intention. But if not working I think we have no choice. 
Thank you for all your infos and your work in buildship. I enjoy to see all the progress done using gradle in eclipse. 

Cheers 
Markus

**Comment by oehme** [comment] 2018-06-07 09:03
Would you be interested in providing a PR to deactivate that logic when WTP isn't present?

**Comment by moley** [comment] 2018-06-07 10:59
yes, this would be nice.

**Comment by moley** [comment] 2018-07-13 06:02
Hi Stefan, 

could you please give me some feedback on this issue? Can you give me advice were to add my test? How do you write tests which need eclipse runtime details? Do you have ui tests, were I can add?

Thanks for you answer

**Comment by oehme** [comment] 2018-07-13 07:02
@donat Can you point @moley in the right direction. We should have an integration test for this, mocking the existence of WTP. I think we did this in other cases already.

**Comment by donat** [comment] 2018-07-13 08:32
The Buildship WTP tests are available [here](https://github.com/eclipse/buildship/blob/release-3.0/org.eclipse.buildship.core.test/src/main/groovy/org/eclipse/buildship/core/workspace/internal/ImportingWtpProjects.groovy). You can set up a development environment [via Oomph](https://github.com/eclipse/buildship/blob/master/docs/development/Setup.md). A few notes here:
- There might be some compilation issues, but activating the [`tooling-e48.target`](https://github.com/eclipse/buildship/blob/release-3.0/tooling-e48.target) target definition file should fix that.
- All tests are executed inside Eclipse. To start the tests from the command line, use the  `./gradlew build` or `./gradlew eclipseTest` commands. From the IDE, just right-click on the test class/package/source dir and select `Run As... > JUnit Plug-In Test`.  For the UI tests you have to uncheck the `Run in UI thread` checkbox in the run configurations page.

Regarding UI tests: IIUC your change only related to the project synchronization logic. Without any change in the UI elements, I think it's not necessary to add any UI tests. Do I miss something?

**Comment by moley** [comment] 2018-07-13 12:08
Hi @donat, 
Thanks for all your infos, I will give it a try on monday

**Comment by donat** [comment] 2018-07-13 12:09
Sure thing. Don't hesitate to reach out to me if you are stuck, I'm happy to help.

**Comment by donat** [comment] 2018-07-16 14:57
The tests should pass. You can check [our CI builds](https://builds.gradle.org/project.html?projectId=Tooling_Buildship&tab=projectOverview) for comparison (credentials: guest/guest). Does the problem happen on the command line (`./gradlew eclipseTest`)?

Judging from the line number, the test failed because Gradle was unable to resolve the dependencies. Can you investigate those issues with the following steps:
- Temporarily add `--debug` to the args to all build invocations in [`GradleArguments`](https://github.com/eclipse/buildship/blob/master/org.eclipse.buildship.core/src/main/java/org/eclipse/buildship/core/configuration/GradleArguments.java).
- Re-execute the tests.

**Comment by Frontrider** [comment] 2018-07-18 11:47
Waiting for the results. In our case eclipse also stops the importing process altogether, leaving us with a fraction of the project accessible from eclipse ,so I'd call it a fatal issue.
eclipse photon

**Comment by moley** [comment] 2018-07-19 09:14
OK, tests are running - I think I have started them as ordinary unit tests by accident

**Comment by moley** [comment] 2018-07-19 12:35
Hi, I am creating a testcase for my scenario. In real life we have a project which does not apply war plugin, but only jar and ear plugin. In my testcase I have the same, but my dependencies get the classpath attribute org.eclipse.jst.component.nodependency. How can I change this to org.eclipse.jst.component.dependency? 

Cheers
Markus

**Comment by moley** [comment] 2018-07-20 06:54
Fixed by pull request [(https://github.com/eclipse/buildship/pull/720)]

**Comment by Frontrider** [comment] 2018-07-20 07:44
Waiting for it.

**Closed** 2018-08-07 12:59 UTC
Labels: an:enhancement, waiting-for:contributor, was:implemented
