### ISSUE TITLE
Enable Smart Import for Gradle project

### ISSUE THREAD

**Issue by jabby** [eclipse/buildship#924] opened 2019-09-22 11:04 UTC
Hello, 

First of all, thanks for your work on Eclipse Buildship. It's really a good plugin.

I am actually doing some Java Gradle project in Eclipse IDE and I miss one handy feature for importing a new Gradle Project in Eclipse IDE. Since, As https://bugs.eclipse.org/bugs/show_bug.cgi?id=500388 is released, I use a lot the Smart Import when I launch Eclipse IDE via my terminal. It works like a charm for Maven project but there is no Smart Import for Gradle. 

Explanation of what is Smart Import. Few years ago there was some work around easily import projects into Eclipse IDE. See https://wiki.eclipse.org/E4/UI/Smart_Import
It's now part of Eclipse Platform.

**Comment by jabby** [comment] 2019-11-05 19:20
For information, I found this issue on the Eclipse Platform bugtracker. I think it is related. 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=500776

**Comment by donat** [comment] 2019-11-07 10:30
#356

**Comment by donat** [comment] 2021-01-29 13:28
Thanks for the input @jabby!

**Comment by donat** [comment] 2021-01-29 13:28
Duplicate of #356.

**Closed by donat** 2021-01-29 13:28 UTC
